config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments, only: [:create]
  end

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  post_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  validates :description, length: { minimum: 250 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
require 'pry'
  def create
    post = Post.find(params[:post_id])
    post.comments.create(comments_params)
    redirect_to post , notice: "El comentario fue publicado con éxito"
  end

  private
    def comments_params
      params.require(:comment).permit(:body).merge(user: current_user)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.update(params[:id], post_params)
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  end

  private
  def post_params
    params.require(:post).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
		markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
		return markdown.render(text).html_safe
	end

	def calculateTime(date)   
		seconds= ((date-DateTime.now)/1.minutes).round.abs * 60    
		puts seconds  	
		mm, ss = seconds.divmod(60) 	
		hh, mm = mm.divmod(60) 	
		dd, hh = hh.divmod(24)    
		if dd != 0
			if dd == 1
				return "#{dd} Dia"
			else
				return "#{dd} Dias"
			end  
		end    
		if hh != 0 
			if hh == 1    
				return "#{hh} Hora"   
			else
				return "#{hh} Horas" 
			end
		end    
		if mm != 0     
			if mm == 1    
				return "#{mm} Hora"   
			else
				return "#{mm} Horas" 
			end   
		end    
		if ss != 0     
			return "#{ss} Segundos"   
		end  	
		return "Algunos segundos" 
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperBlog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
</head>

<body>

  <nav class="navbar bg-primary navbar-dark navbar-expand-sm border-bottom box-shadow">
    <%= link_to "SuperBlog", root_path, class: "navbar-brand " %>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">

      <ul class="navbar-nav ml-auto ">
        <% if user_signed_in? %>
        <li class="nav-link"><%=current_user.email%></li>
        <li class="nav-item">
          <%= link_to "Salir", destroy_user_session_path, method: "delete", :class => "nav-link"  %>
        </li>

          <% else %>
          <li class="nav-item">
            <%= link_to "Ingresar", new_user_session_path, :class => "nav-link"  %>
          </li>
          <li class="nav-item ">
            <%= link_to "Regístrarse", new_user_registration_path, :class => "btn btn-light  "  %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container" style="margin-top:30px">
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_comment.html.erb
<div class="card">
  <h5 class="card-header"><%= comment.user.email %>  hace <%=calculateTime(comment.created_at)%></h5>
  <div class="card-body">
    <p class="card-text"><%= markdown(comment.body) %></p>
  </div>
</div>
<br>

app/views/posts/_form.html.erb
<div id="post-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title text-center"><%= title %></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>

      </div>
      <div class="errors_validation"></div>


      <%= form_for @post, remote: true do |f| %>
      <div class="modal-body">
        <div class="alert alert-danger" role="alert" style="display: none;"></div> <!-- como se activa? -->
        <div class="form-group">
          <%= f.text_field :title, class: "form-control input-lg", placeholder: "Titulo del Post" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, class: "form-control input-lg", placeholder: "Descripción del post" , rows: 10  %>
        </div>
      </div>

      <div class="modal-footer">
        <%= f.submit class: "btn btn-dark btn-lg btn-block" %>
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/posts/_row.html.erb
<div id="<%= post.id %>" class="card">
    <div role="tab" id="heading<%= post.id %>">
        <div class="card-header">
        <i class="card-action fa fa-file-text-o" aria-hidden="true"></i>
        <a
            data-toggle="collapse"
            data-parent="#accordion"
            href="#collapse<%= post.id %>"
            aria-expanded="false"
            aria-controls="collapse<%= post.id %>"
            class="card-header-content collapsed"
        >
            <div>
            <h3 class="card-title"><%=post.title%></h3>
            <p class="card-author"><%= post.user.email %> Hace <%=calculateTime(post.created_at)%></p>
            </div>
        </a>
        <div class="card-actions">              
            <% if user_signed_in? && current_user.id == post.user_id%>
                <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, post, method: :delete, data: { confirm: "¿Estás seguro de eliminar este producto?", remote: true }, :class => "card-action"  %>
                <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_post_path(post), remote: true, :class => "card-action"   %>
            <% end %>
            <%= link_to '<i class="fa fa-angle-right" aria-hidden="true"></i>'.html_safe, post, :class => "card-action"  %>

        </div>
        </div>
    </div>

    <div
        id="collapse<%= post.id %>"
        class="collapse"
        role="tabpanel"
        aria-labelledby="heading<%= post.id %>"
        aria-expanded="false"
        style=""
    >
        <div class="card-block">
        <%= markdown(post.description[0, 250]) %>
        </div>
    </div>
</div>

app/views/posts/create.js.erb
<% if @post.errors.empty? %>
  $('.new_post').append(' <%= j render "row", post: @post %>');
  growl("success", "El post ha sido creado con éxito!", '.alerta_index');
  $('#post-modal').modal('hide');

<% else %>
  <% @post.errors.full_messages.each do |msg| %>
    growl("danger", "<%= msg%>", '.errors_validation');
  <% end %>
<% end %>

app/views/posts/destroy.js.erb
  $('.new_post div#<%= @post.id %>').remove();
  growl("success", "El post fue eliminado con éxito!", '.alerta_index')

app/views/posts/edit.js.erb
$('<%= j render "form", title: "Editar Post" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/posts/index.html.erb
<div class="alerta_index">
</div>
<% if flash[:notice] %>
<div class="alert alert-success alert-dismissible fade show"><button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= flash[:notice] %>
</div>
<% end %>
<section>
  <div class="container">
    <div class="row">

      <div class="col-md-10 offset-md-1">
        <div class="bd-example" data-example-id="">
          <div id="accordion" role="tablist" aria-multiselectable="true">

            <% if user_signed_in? %>
            <%= link_to "Publicar Post", new_post_path, remote: true, class: "btn btn-outline-dark btn-sm" %>
            <% end %>
          </div>
          <br>
          <div class="new_post">
            <% @posts.each do |post| %>
            <%= render "row", post: post %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/posts/new.js.erb
$('<%= j render "form", title: "Nuevo Post" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/posts/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show"><button type="button" class="close" data-dismiss="alert">&times;</button><%= flash[:notice] %></div>
<% end %>
<div class="row justify-content-center">
    <div class="col-sm-10 ">
      <h1><%= @post.title %></h1> <hr>
      <p><%= markdown(@post.description) %></p>
      <hr>
      <div class="reload_comment">
        <% @post.comments.each do |comment| %>
          <%= render "comment", comment: comment %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <%= form_for [@post, @post.comments.build], remote: true  do |f| %>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "Agregar comentario" %>
          </div>

          <div class="actions text-right">
            <%= f.submit "Comentar", class: "btn btn-outline-dark show" %>
          </div>
        <% end %>
      <% end %>
<br>
    </div>
  </div>

app/views/posts/update.js.erb
<% if @post.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('.new_post div#<%= @post.id %>').replaceWith(' <%= j render "row", post: @post %>');
  growl("success", "El post ha sido modificado con éxito!", '.alerta_index')
  $('#post-modal').modal('hide');
<% else %>

<% @post.errors.full_messages.each do |msg| %>
  growl("danger", "<%= msg%>", '.errors_validation');
<% end %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>